require("lazy_init")
require("core/set")
require("core/remap")
-- require("plugins/nvim-treesitter")
-- require("plugins/colorscheme")
-- require("plugins/telescope")
-- require("plugins/lualine")
-- require("plugins/gitsigns")
-- require("plugins/mini-nvim")
-- require("plugins/nvim-cmp")
-- require("plugins/neodev")
-- require("plugins/copilot")
-- require("plugins/fugitive")
-- require("lsp/lspconfig")
